<?php

namespace backend\models;

use Yii;

/**
 * This is the model class for table "menu".
 *
 * @property int $id
 * @property int $id_prato
 * @property int $id_bebida
 * @property int $id_sobremesa
 * @property string $preco
 * @property string $imagem
 *
 * @property Sobremesa $sobremesa
 * @property Prato $prato
 * @property Bebida $bebida
 * @property Pedido[] $pedidos
 */
class Menu extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'menu';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['id_prato', 'id_bebida', 'id_sobremesa', 'preco', 'imagem'], 'required'],
            [['id_prato', 'id_bebida', 'id_sobremesa'], 'integer'],
            [['preco'], 'number'],
            [['imagem'], 'string', 'max' => 255],
            [['id_sobremesa'], 'exist', 'skipOnError' => true, 'targetClass' => Sobremesa::className(), 'targetAttribute' => ['id_sobremesa' => 'id']],
            [['id_prato'], 'exist', 'skipOnError' => true, 'targetClass' => Prato::className(), 'targetAttribute' => ['id_prato' => 'id']],
            [['id_bebida'], 'exist', 'skipOnError' => true, 'targetClass' => Bebida::className(), 'targetAttribute' => ['id_bebida' => 'id']],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'id_prato' => 'Id Prato',
            'id_bebida' => 'Id Bebida',
            'id_sobremesa' => 'Id Sobremesa',
            'preco' => 'Preco',
            'imagem' => 'Imagem',
        ];
    }

    public function delete()
    {
        if (file_exists('img/menus/' . $this->imagem)) {
            unlink('img/menus/' . $this->imagem);
        }

        return parent::delete(); // TODO: Change the autogenerated stub
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getSobremesa()
    {
        return $this->hasOne(Sobremesa::className(), ['id' => 'id_sobremesa']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getPrato()
    {
        return $this->hasOne(Prato::className(), ['id' => 'id_prato']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getBebida()
    {
        return $this->hasOne(Bebida::className(), ['id' => 'id_bebida']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getPedidos()
    {
        return $this->hasMany(Pedido::className(), ['id_menu' => 'id']);
    }
}
