<?php

namespace backend\models;

use Yii;

/**
 * This is the model class for table "sobremesa".
 *
 * @property int $id
 * @property string $descricao
 * @property string $preco
 * @property string $imagem
 *
 * @property Itens[] $itens
 */
class Sobremesa extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'sobremesa';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['descricao', 'preco', 'imagem'], 'required'],
            [['preco'], 'number'],
            [['descricao'], 'string', 'max' => 100],
            [['imagem'], 'string', 'max' => 255],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'descricao' => 'Descricao',
            'preco' => 'Preco',
            'imagem' => 'Imagem',
        ];
    }

    public function delete()
    {
        if (file_exists('img/sobremesa/' . $this->imagem)) {
            unlink('img/sobremesa/' . $this->imagem);
        }

        return parent::delete(); // TODO: Change the autogenerated stub
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getItens()
    {
        return $this->hasMany(Itens::className(), ['id_sobremesa' => 'id']);
    }
}
