<?php

namespace backend\models;

use ErrorException;
use stdClass;
use Yii;
use backend\mosquitto\phpMQTT;
/**
 * This is the model class for table "sobremesa".
 *
 * @property int $id
 * @property string $descricao
 * @property string $preco
 * @property string $imagem
 *
 * @property Itens[] $itens
 */
class Sobremesa extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'sobremesa';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['descricao', 'preco', 'imagem'], 'required'],
            [['preco'], 'number'],
            [['descricao'], 'string', 'max' => 100],
            [['imagem'], 'string', 'max' => 255],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'descricao' => 'Descricao',
            'preco' => 'Preco',
            'imagem' => 'Imagem',
        ];
    }

    public function delete()
    {
        if (file_exists('img/sobremesa/' . $this->imagem)) {
            unlink('img/sobremesa/' . $this->imagem);
        }

        return parent::delete(); // TODO: Change the autogenerated stub
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getItens()
    {
        return $this->hasMany(Itens::className(), ['id_sobremesa' => 'id']);
    }

    public function afterSave($insert, $changedAttributes)
    {
        parent::afterSave($insert, $changedAttributes);
        //Obter dados do registo em causa
        $id = $this->id;
        $descricao = $this->descricao;
        $preco = $this->preco;
        $imagem = $this->imagem;

        $myObj = new stdClass();
        $myObj->id = $id;
        $myObj->descricao = $descricao;
        $myObj->preco = $preco;
        $myObj->imagem = $imagem;
        $myJSON = json_encode($myObj);

        if($insert) $this->FazPublish("INSERT",$myJSON);
        else $this->FazPublish("UPDATE",$myJSON);
    }

    public function afterDelete()
    {
        parent::afterDelete();
        $id = $this->id;
        $myObj = new stdClass();
        $myObj->id=$id;
        $myJSON = json_encode($myObj);
        $this->FazPublish("DELETE",$myJSON);
    }

    public function FazPublish($canal,$msg)
    {
        $server = "127.0.0.1";
        $port = 1883;
        $username = ""; // set your username
        $password = ""; // set your password
        $client_id = "Sobremesa"; // unique!
        $mqtt = new phpMQTT($server, $port, $client_id);
        try{
            $mqtt->connect(true, NULL, $username, $password);
            $mqtt->publish($canal, $msg, 0);
            $mqtt->close();
        }catch (ErrorException $e){

        }
    }
}
